# Generated by Django 5.2.2 on 2025-06-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('libelle', models.CharField(max_length=255)),
                ('type_depense', models.CharField(choices=[('ajour_ouvriers', 'أجور العمال'), ('factures', 'الفواتير'), ('location', 'الكراء'), ('divers', 'مصاريف أخرى'), ('dettes', 'ديون'), ('dettes_privees', 'ديون خاصة'), ('participants', 'مساهمين')], max_length=50)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement')], max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
