# Generated by Django 5.2.6 on 2025-11-05 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('libelle', models.CharField(max_length=255)),
                ('type_depense', models.CharField(choices=[('أجور العمال', 'أجور العمال'), ('الفواتير', 'الفواتير'), ('الكراء', 'الكراء'), ('سلع تالفة', 'سلع تالفة'), ('مصاريف أخرى', 'مصاريف أخرى'), ('ديون', 'ديون'), ('ديون خاصة', 'ديون خاصة'), ('مساهمين', 'مساهمين')], max_length=50)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèces'), ('cheque', 'Chèque'), ('ccp', 'Ccp')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
