# Generated by Django 5.2.2 on 2025-06-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
