# Generated by Django 5.0.3 on 2025-07-14 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_alter_depense_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='depense',
            name='mode_paiement',
            field=models.CharField(choices=[('espece', 'Espèces'), ('cheque', 'Chèque'), ('ccp', 'ccp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='depense',
            name='type_depense',
            field=models.CharField(choices=[('paye_ouvriers', 'أجور العمال'), ('factures', 'الفواتير'), ('location', 'الكراء'), ('produit_casse', 'سلع تالفة'), ('divers', 'مصاريف أخرى'), ('dettes', 'ديون'), ('dettes_privees', 'ديون خاصة'), ('participants', 'مساهمين')], max_length=50),
        ),
    ]
