# Generated by Django 5.0.3 on 2025-07-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0003_depense_utilisateur_alter_depense_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='mode_paiement',
            field=models.CharField(choices=[('espece', 'Espèces'), ('cheque', 'Chèque'), ('ccp', 'Ccp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='depense',
            name='type_depense',
            field=models.CharField(choices=[('أجور العمال', 'أجور العمال'), ('الفواتير', 'الفواتير'), ('الكراء', 'الكراء'), ('سلع تالفة', 'سلع تالفة'), ('مصاريف أخرى', 'مصاريف أخرى'), ('ديون', 'ديون'), ('ديون خاصة', 'ديون خاصة'), ('مساهمين', 'مساهمين')], max_length=50),
        ),
    ]
