# Generated by Django 5.2.2 on 2025-06-16 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
        ('parametres', '0001_initial'),
        ('produits', '0006_produit_est_supprime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchatGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('somme_payee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('somme_restante', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('achat_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='achats.achatgroupe')),
                ('magasin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.magasin')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.produit')),
            ],
        ),
    ]
