# Generated by Django 5.0.3 on 2025-07-21 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_achatgroupe_ligneachat'),
        ('authentification', '0009_remove_client_numero_and_more'),
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatgroupe',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentification.fournisseur', verbose_name='fournisseur'),
        ),
        migrations.AlterField(
            model_name='ligneachat',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.magasin'),
        ),
    ]
