# Generated by Django 5.2.6 on 2025-09-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_alter_achatgroupe_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneachat',
            name='nouveaux_codes_barres',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
