# Generated by Django 5.2.2 on 2025-06-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0005_fournisseur'),
        ('parametres', '0001_initial'),
        ('produits', '0009_produit_taux_benefice_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteFacilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_choisi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_mois', models.PositiveIntegerField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_verse', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_restant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montants_par_mois', models.JSONField(default=list)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.client', verbose_name='الزبون')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
    ]
