# Generated by Django 5.0.3 on 2025-07-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_remove_client_numero_and_more'),
        ('parametres', '0001_initial'),
        ('produits', '0011_alter_produit_prix_achat_alter_produit_prix_vente_10_and_more'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.client', verbose_name='الزبون')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.magasin')),
            ],
        ),
        migrations.CreateModel(
            name='LigneVenteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.ventecache')),
            ],
        ),
    ]
