# Generated by Django 5.0.3 on 2025-07-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_ventecache_ligneventecache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventecache',
            name='magasin',
        ),
    ]
