# Generated by Django 5.0.3 on 2025-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_remove_ventecache_magasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneventecache',
            name='codes_barres_utilises',
            field=models.JSONField(default=list),
        ),
    ]
