# Generated by Django 5.0.3 on 2025-07-28 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0012_alter_produit_codes_barres'),
        ('ventes', '0005_ventecache_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventefacilite',
            name='magasin',
        ),
        migrations.RemoveField(
            model_name='ventefacilite',
            name='prix_choisi',
        ),
        migrations.RemoveField(
            model_name='ventefacilite',
            name='produit',
        ),
        migrations.CreateModel(
            name='LigneVenteFacilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.ventefacilite')),
            ],
        ),
    ]
