# Generated by Django 5.0.3 on 2025-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_remove_ventefacilite_magasin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneventefacilite',
            name='codes_barres_utilises',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
