# Generated by Django 5.0.3 on 2025-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0008_ventefacilite_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventefacilite',
            name='montant_mensuel',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='ventefacilite',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='ventefacilite',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='ventefacilite',
            name='montant_verse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
