# Generated by Django 5.0.3 on 2025-07-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0010_alter_ventefacilite_montant_mensuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventefacilite',
            name='montant_mensuel',
            field=models.DecimalField(decimal_places=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='ventefacilite',
            name='montant_restant',
            field=models.DecimalField(decimal_places=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='ventefacilite',
            name='montant_total',
            field=models.DecimalField(decimal_places=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='ventefacilite',
            name='montant_verse',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1000),
        ),
    ]
