# Generated by Django 5.0.3 on 2025-08-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0011_alter_ventefacilite_montant_mensuel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventefacilite',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='ventefacilite',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
