# Generated by Django 5.0.3 on 2025-08-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0012_alter_ventefacilite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventefacilite',
            name='montant_paye_effectif',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1000),
        ),
    ]
