# Generated by Django 5.0.3 on 2025-08-03 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0013_ventefacilite_montant_paye_effectif'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=1000)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.ventefacilite')),
            ],
        ),
    ]
