# Generated by Django 5.0.3 on 2025-08-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0014_paiementvente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementvente',
            name='month_index',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='paiementvente',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiementvente',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
