# Generated by Django 5.0.3 on 2025-08-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0015_paiementvente_month_index_paiementvente_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventefacilite',
            name='montants_par_mois',
        ),
        migrations.AddField(
            model_name='ventefacilite',
            name='mois_status',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
