# Generated by Django 5.0.3 on 2025-08-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0016_remove_ventefacilite_montants_par_mois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventefacilite',
            name='montants_par_mois',
            field=models.JSONField(default=list),
        ),
    ]
