# Generated by Django 5.0.3 on 2025-08-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0017_ventefacilite_montants_par_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventefacilite',
            name='solde_regle',
            field=models.BooleanField(default=False),
        ),
    ]
