# Generated by Django 5.2.6 on 2025-11-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='اسم المحل')),
                ('adresse', models.TextField(verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'المحل',
                'verbose_name_plural': 'المحلات',
            },
        ),
    ]
