# Generated by Django 5.2.6 on 2025-11-05 16:04

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assurance_militaire', models.CharField(max_length=50, null=True, verbose_name='assurance')),
                ('date_expedition', models.DateField(null=True, verbose_name='date_expedition')),
                ('nom_famille_ar', models.CharField(max_length=100, null=True, verbose_name='اللقب (عربي)')),
                ('prenom_ar', models.CharField(max_length=100, null=True, verbose_name='الاسم (عربي)')),
                ('nom_famille_fr', models.CharField(max_length=100, null=True, verbose_name='Nom de famille (français)')),
                ('prenom_fr', models.CharField(max_length=100, null=True, verbose_name='Prénom (français)')),
                ('nom_pere', models.CharField(max_length=100, null=True, verbose_name='إسم الأب / Nom du père')),
                ('nom_mere', models.CharField(max_length=100, null=True, verbose_name='إسم الأم / Nom de la mère')),
                ('numero_national', models.CharField(max_length=50, null=True, unique=True, verbose_name='الرقم الوطني / Numéro national')),
                ('date_naissance', models.DateField(null=True, verbose_name='تاريخ الازدياد / Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, null=True, verbose_name='مكان الازدياد / Lieu de naissance')),
                ('adresse', models.TextField(verbose_name='العنوان / Adresse')),
                ('telephone', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9+]+$', 'Numéro de téléphone invalide')], verbose_name='رقم الهاتف / Téléphone')),
                ('profession', models.CharField(max_length=100, verbose_name='المهنة / Profession')),
                ('revenu', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الدخل / Revenu')),
                ('type_piece_identite', models.CharField(choices=[('بطاقة التعريف الوطنية ', "بطاقة التعريف الوطنية / Carte d'identité"), ('جواز السفر ', 'جواز السفر / Passeport'), ('رخصة السياقة ', 'رخصة السياقة / Permis de conduire')], max_length=100, verbose_name='نوع وثيقة التعريف / Type de pièce')),
                ('numero_piece_identite', models.CharField(max_length=100, null=True, verbose_name='رقم الوثيقة / Numéro de pièce')),
                ('date_emission_piece', models.DateField(null=True, verbose_name="تاريخ الإصدار / Date d'émission")),
                ('jour', models.CharField(max_length=2, null=True)),
                ('lieu_emission_piece', models.CharField(blank=True, max_length=100, null=True, verbose_name="مكان الإصدار / Lieu d'émission")),
                ('ccp', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب البنكي / Numéro de compte')),
                ('cle', models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='المفتاح / Clé')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرمز السري / Code secret')),
                ('dette_initiale', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ديون ابتدائية / Dette initiale')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات / Notes')),
                ('statut', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحالة / Statut')),
                ('bloque', models.BooleanField(default=False, verbose_name='محظور / Bloqué')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'عميل / Client',
                'verbose_name_plural': 'العملاء / Clients',
                'ordering': ['nom_famille_fr', 'prenom_fr'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='اسم الممون')),
                ('adresse', models.TextField(verbose_name='عنوان الممون')),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+]+$', 'رقم الهاتف غير صالح')], verbose_name='رقم الهاتف')),
                ('wilaya', models.CharField(choices=[('01', 'Adrar / أدرار'), ('02', 'Chlef / الشلف'), ('03', 'Laghouat / الأغواط'), ('04', 'Oum El Bouaghi / أم البواقي'), ('05', 'Batna / باتنة'), ('06', 'Béjaïa / بجاية'), ('07', 'Biskra / بسكرة'), ('08', 'Béchar / بشار'), ('09', 'Blida / البليدة'), ('10', 'Bouira / البويرة'), ('11', 'Tamanrasset / تمنراست'), ('12', 'Tébessa / تبسة'), ('13', 'Tlemcen / تلمسان'), ('14', 'Tiaret / تيارت'), ('15', 'Tizi Ouzou / تيزي وزو'), ('16', 'Alger / الجزائر'), ('17', 'Djelfa / الجلفة'), ('18', 'Jijel / جيجل'), ('19', 'Sétif / سطيف'), ('20', 'Saïda / سعيدة'), ('21', 'Skikda / سكيكدة'), ('22', 'Sidi Bel Abbès / سيدي بلعباس'), ('23', 'Annaba / عنابة'), ('24', 'Guelma / قالمة'), ('25', 'Constantine / قسنطينة'), ('26', 'Médéa / المدية'), ('27', 'Mostaganem / مستغانم'), ('28', "M'Sila / المسيلة"), ('29', 'Mascara / معسكر'), ('30', 'Ouargla / ورقلة'), ('31', 'Oran / وهران'), ('32', 'El Bayadh / البيض'), ('33', 'Illizi / إيليزي'), ('34', 'Bordj Bou Arréridj / برج بوعريريج'), ('35', 'Boumerdès / بومرداس'), ('36', 'El Tarf / الطارف'), ('37', 'Tindouf / تندوف'), ('38', 'Tissemsilt / تسمسيلت'), ('39', 'El Oued / الوادي'), ('40', 'Khenchela / خنشلة'), ('41', 'Souk Ahras / سوق أهراس'), ('42', 'Tipaza / تيبازة'), ('43', 'Mila / ميلة'), ('44', 'Aïn Defla / عين الدفلى'), ('45', 'Naâma / النعامة'), ('46', 'Aïn Témouchent / عين تيموشنت'), ('47', 'Ghardaïa / غرداية'), ('48', 'Relizane / غليزان'), ('49', 'Timimoun / تيميمون'), ('50', 'Bordj Badji Mokhtar / برج باجي مختار'), ('51', 'Ouled Djellal / أولاد جلال'), ('52', 'Béni Abbès / بني عباس'), ('53', 'In Salah / عين صالح'), ('54', 'In Guezzam / عين قزام'), ('55', 'Touggourt / تقرت'), ('56', 'Djanet / جانت'), ('57', "El M'Ghair / المغير"), ('58', 'El Menia / المنيعة')], max_length=2, verbose_name='الولاية')),
                ('dettes_initiales', models.DecimalField(decimal_places=2, default=0, help_text='المبلغ الابتدائي للديون عند إضافة الممون', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الديون الأولية')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ممون',
                'verbose_name_plural': 'الممونون',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('vendeur', 'Vendeur'), ('magasinier', 'Magasinier')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=list)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FichierClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ملف مرفق / Fichier joint')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='authentification.client')),
            ],
        ),
    ]
