# Generated by Django 5.2.2 on 2025-06-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='الرقم')),
                ('nom_famille', models.CharField(max_length=100, verbose_name='اللقب')),
                ('prenom', models.CharField(max_length=100, verbose_name='الاسم')),
                ('nom_pere', models.CharField(max_length=100, verbose_name='إسم الأب')),
                ('nom_mere', models.CharField(max_length=100, verbose_name='إسم الأم')),
                ('numero_national', models.CharField(max_length=50, unique=True, verbose_name='الرقم الوطني')),
                ('date_naissance', models.DateField(verbose_name='تاريخ الازدياد')),
                ('adresse', models.TextField(verbose_name='العنوان')),
                ('profession', models.CharField(max_length=100, verbose_name='المهنة')),
                ('revenu', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الدخل')),
                ('piece_identite', models.CharField(max_length=100, verbose_name='وثيقة التعريف')),
                ('date_emission', models.DateField(verbose_name='الإصدار')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
    ]
