# Generated by Django 5.2.2 on 2025-06-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ccp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب'),
        ),
        migrations.AddField(
            model_name='client',
            name='cle',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='المفتاح'),
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرمز السري'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dette_initiale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ديون ابتدائية'),
        ),
        migrations.AddField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.CreateModel(
            name='FichierClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='client_files/%Y/%m/%d/', verbose_name='ملف مرفق')),
                ('nom', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='authentification.client')),
            ],
        ),
    ]
