# Generated by Django 5.2.2 on 2025-06-09 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_client_ccp_client_cle_client_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nom_famille_fr', 'prenom_fr'], 'verbose_name': 'عميل / Client', 'verbose_name_plural': 'العملاء / Clients'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_emission',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nom_famille',
        ),
        migrations.RemoveField(
            model_name='client',
            name='piece_identite',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
        migrations.AddField(
            model_name='client',
            name='date_emission_piece',
            field=models.DateField(null=True, verbose_name="تاريخ الإصدار / Date d'émission"),
        ),
        migrations.AddField(
            model_name='client',
            name='date_expiration_piece',
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ انتهاء الصلاحية / Date d'expiration"),
        ),
        migrations.AddField(
            model_name='client',
            name='lieu_emission_piece',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="مكان الإصدار / Lieu d'émission"),
        ),
        migrations.AddField(
            model_name='client',
            name='lieu_naissance',
            field=models.CharField(max_length=100, null=True, verbose_name='مكان الازدياد / Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='client',
            name='nom_famille_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='اللقب (عربي)'),
        ),
        migrations.AddField(
            model_name='client',
            name='nom_famille_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom de famille (français)'),
        ),
        migrations.AddField(
            model_name='client',
            name='numero_piece_identite',
            field=models.CharField(max_length=100, null=True, verbose_name='رقم الوثيقة / Numéro de pièce'),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='الاسم (عربي)'),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Prénom (français)'),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9+]+$', 'Numéro de téléphone invalide')], verbose_name='رقم الهاتف / Téléphone'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_piece_identite',
            field=models.CharField(choices=[('CI', "بطاقة التعريف الوطنية / Carte d'identité"), ('PASS', 'جواز السفر / Passeport'), ('PERMIS', 'رخصة السياقة / Permis de conduire')], default='CI', max_length=10, verbose_name='نوع وثيقة التعريف / Type de pièce'),
        ),
        migrations.AddField(
            model_name='fichierclient',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الملف / Description'),
        ),
        migrations.AddField(
            model_name='fichierclient',
            name='type_fichier',
            field=models.CharField(choices=[('IDENTITE', "وثيقة الهوية / Pièce d'identité"), ('JUSTIF_DOM', 'إثبات العنوان / Justificatif de domicile'), ('CONTRAT', 'عقد / Contrat'), ('AUTRE', 'آخر / Autre')], default='IDENTITE', max_length=20, verbose_name='نوع الملف / Type de fichier'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(verbose_name='العنوان / Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ccp',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='رقم الحساب البنكي / Numéro de compte'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cle',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='المفتاح / Clé'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرمز السري / Code secret'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(null=True, verbose_name='تاريخ الازدياد / Date de naissance'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dette_initiale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ديون ابتدائية / Dette initiale'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_mere',
            field=models.CharField(max_length=100, null=True, verbose_name='إسم الأم / Nom de la mère'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_pere',
            field=models.CharField(max_length=100, null=True, verbose_name='إسم الأب / Nom du père'),
        ),
        migrations.AlterField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات / Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero',
            field=models.CharField(max_length=50, null=True, verbose_name='الرقم / Numéro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_national',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='الرقم الوطني / Numéro national'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profession',
            field=models.CharField(max_length=100, verbose_name='المهنة / Profession'),
        ),
        migrations.AlterField(
            model_name='client',
            name='revenu',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الدخل / Revenu'),
        ),
        migrations.AlterField(
            model_name='fichierclient',
            name='fichier',
            field=models.FileField(upload_to='client_files/%Y/%m/%d/', verbose_name='ملف مرفق / Fichier joint'),
        ),
        migrations.AlterField(
            model_name='fichierclient',
            name='nom',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم الملف / Nom du fichier'),
        ),
    ]
