# Generated by Django 5.2.2 on 2025-06-09 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_client_options_remove_client_date_emission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='اسم الممون')),
                ('adresse', models.TextField(verbose_name='عنوان الممون')),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+]+$', 'رقم الهاتف غير صالح')], verbose_name='رقم الهاتف')),
                ('wilaya', models.CharField(choices=[('01', 'Adrar / أدرار'), ('02', 'Chlef / الشلف'), ('03', 'Laghouat / الأغواط'), ('04', 'Oum El Bouaghi / أم البواقي'), ('05', 'Batna / باتنة'), ('06', 'Béjaïa / بجاية'), ('07', 'Biskra / بسكرة'), ('08', 'Béchar / بشار'), ('09', 'Blida / البليدة'), ('10', 'Bouira / البويرة'), ('11', 'Tamanrasset / تمنراست'), ('12', 'Tébessa / تبسة'), ('13', 'Tlemcen / تلمسان'), ('14', 'Tiaret / تيارت'), ('15', 'Tizi Ouzou / تيزي وزو'), ('16', 'Alger / الجزائر'), ('17', 'Djelfa / الجلفة'), ('18', 'Jijel / جيجل'), ('19', 'Sétif / سطيف'), ('20', 'Saïda / سعيدة'), ('21', 'Skikda / سكيكدة'), ('22', 'Sidi Bel Abbès / سيدي بلعباس'), ('23', 'Annaba / عنابة'), ('24', 'Guelma / قالمة'), ('25', 'Constantine / قسنطينة'), ('26', 'Médéa / المدية'), ('27', 'Mostaganem / مستغانم'), ('28', "M'Sila / المسيلة"), ('29', 'Mascara / معسكر'), ('30', 'Ouargla / ورقلة'), ('31', 'Oran / وهران'), ('32', 'El Bayadh / البيض'), ('33', 'Illizi / إيليزي'), ('34', 'Bordj Bou Arréridj / برج بوعريريج'), ('35', 'Boumerdès / بومرداس'), ('36', 'El Tarf / الطارف'), ('37', 'Tindouf / تندوف'), ('38', 'Tissemsilt / تسمسيلت'), ('39', 'El Oued / الوادي'), ('40', 'Khenchela / خنشلة'), ('41', 'Souk Ahras / سوق أهراس'), ('42', 'Tipaza / تيبازة'), ('43', 'Mila / ميلة'), ('44', 'Aïn Defla / عين الدفلى'), ('45', 'Naâma / النعامة'), ('46', 'Aïn Témouchent / عين تيموشنت'), ('47', 'Ghardaïa / غرداية'), ('48', 'Relizane / غليزان'), ('49', 'Timimoun / تيميمون'), ('50', 'Bordj Badji Mokhtar / برج باجي مختار'), ('51', 'Ouled Djellal / أولاد جلال'), ('52', 'Béni Abbès / بني عباس'), ('53', 'In Salah / عين صالح'), ('54', 'In Guezzam / عين قزام'), ('55', 'Touggourt / تقرت'), ('56', 'Djanet / جانت'), ('57', "El M'Ghair / المغير"), ('58', 'El Menia / المنيعة')], max_length=2, verbose_name='الولاية')),
                ('dettes_initiales', models.DecimalField(decimal_places=2, default=0, help_text='المبلغ الابتدائي للديون عند إضافة الممون', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الديون الأولية')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ممون',
                'verbose_name_plural': 'الممونون',
                'ordering': ['nom'],
            },
        ),
    ]
