# Generated by Django 5.0.3 on 2025-07-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichierclient',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='fichierclient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fichierclient',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='fichierclient',
            name='type_fichier',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendeur', 'Vendeur'), ('magasinier', 'Magasinier')], max_length=20),
        ),
    ]
