# Generated by Django 5.0.3 on 2025-07-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_remove_fichierclient_date_ajout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_expiration_piece',
        ),
    ]
