# Generated by Django 5.0.3 on 2025-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_remove_client_date_expiration_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='jour',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
