# Generated by Django 5.0.3 on 2025-07-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_client_jour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='numero',
        ),
        migrations.AlterField(
            model_name='client',
            name='type_piece_identite',
            field=models.CharField(choices=[('بطاقة التعريف الوطنية ', "بطاقة التعريف الوطنية / Carte d'identité"), ('جواز السفر ', 'جواز السفر / Passeport'), ('رخصة السياقة ', 'رخصة السياقة / Permis de conduire')], default='CI', max_length=100, verbose_name='نوع وثيقة التعريف / Type de pièce'),
        ),
    ]
