# Generated by Django 5.0.3 on 2025-07-29 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_remove_client_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ccp',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='رقم الحساب البنكي / Numéro de compte'),
        ),
    ]
