# Generated by Django 5.0.3 on 2025-07-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0010_alter_client_ccp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ccp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب البنكي / Numéro de compte'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_national',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='الرقم الوطني / Numéro national'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_piece_identite',
            field=models.CharField(choices=[('بطاقة التعريف الوطنية ', "بطاقة التعريف الوطنية / Carte d'identité"), ('جواز السفر ', 'جواز السفر / Passeport'), ('رخصة السياقة ', 'رخصة السياقة / Permis de conduire')], max_length=100, verbose_name='نوع وثيقة التعريف / Type de pièce'),
        ),
    ]
