# Generated by Django 5.0.3 on 2025-08-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_alter_client_ccp_alter_client_numero_national_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bloque',
            field=models.BooleanField(default=False, verbose_name='محظور / Bloqué'),
        ),
        migrations.AddField(
            model_name='client',
            name='statut',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الحالة / Statut'),
        ),
    ]
