# Generated by Django 5.0.3 on 2025-08-06 11:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0012_client_bloque_client_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierclient',
            name='fichier',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='ملف مرفق / Fichier joint'),
        ),
    ]
