# Generated by Django 5.2.2 on 2025-08-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0013_alter_fichierclient_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assurance_militaire',
            field=models.CharField(max_length=50, null=True, verbose_name='assurance'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_expedition',
            field=models.DateField(null=True, verbose_name='date_expedition'),
        ),
    ]
