# Generated by Django 5.2.6 on 2025-09-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_client_assurance_militaire_client_date_expedition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
