# Generated by Django 5.2.6 on 2025-09-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0015_customuser_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
