# Generated by Django 5.2.6 on 2025-11-05 16:05

import django.db.models.deletion
import django.utils.timezone
import transfert.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('codes_barres_transferes', models.JSONField(default=list, verbose_name='Codes-barres transférés')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('heure', models.TimeField(default=transfert.models.get_current_time, verbose_name='Time')),
                ('produit_supprime', models.BooleanField(default=False, verbose_name='Produit supprimé')),
                ('magasin_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='parametres.magasin', verbose_name='Magasin destination')),
                ('magasin_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='parametres.magasin', verbose_name='Magasin source')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit', verbose_name='Produit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transfert',
                'verbose_name_plural': 'Transferts',
                'ordering': ['-date', '-heure'],
            },
        ),
    ]
