# Generated by Django 5.2.2 on 2025-06-14 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
        ('produits', '0005_remove_produit_codebar_remove_produit_quantite_and_more'),
        ('transfert', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfert',
            options={'ordering': ['-date', '-heure'], 'verbose_name': 'Transfer', 'verbose_name_plural': 'Transfers'},
        ),
        migrations.RemoveField(
            model_name='transfert',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transfert',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transfert',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='transfert',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='heure',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='produit_supprime',
            field=models.BooleanField(default=False, verbose_name='Product Deleted'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='codes_barres_transferes',
            field=models.JSONField(default=list, verbose_name='Transferred Barcodes'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='magasin_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='parametres.magasin', verbose_name='Destination Store'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='magasin_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='parametres.magasin', verbose_name='Source Store'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='quantite',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
    ]
