# Generated by Django 5.2.2 on 2025-06-16 10:09

import django.db.models.deletion
import transfert.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
        ('produits', '0005_remove_produit_codebar_remove_produit_quantite_and_more'),
        ('transfert', '0002_alter_transfert_options_remove_transfert_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfert',
            options={'ordering': ['-date', '-heure'], 'verbose_name': 'Transfert', 'verbose_name_plural': 'Transferts'},
        ),
        migrations.AlterField(
            model_name='transfert',
            name='codes_barres_transferes',
            field=models.JSONField(default=list, verbose_name='Codes-barres transférés'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='heure',
            field=models.TimeField(default=transfert.models.get_current_time, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='magasin_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='parametres.magasin', verbose_name='Magasin destination'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='magasin_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='parametres.magasin', verbose_name='Magasin source'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='produit_supprime',
            field=models.BooleanField(default=False, verbose_name='Produit supprimé'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='quantite',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
