# Generated by Django 5.2.6 on 2025-11-05 16:05

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, null=True)),
                ('nom', models.CharField(max_length=100, verbose_name='اسم المنتوج / Nom produit')),
                ('famille', models.CharField(max_length=100, verbose_name='العائلة / Famille')),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='العلامة / Marque')),
                ('codes_barres', models.JSONField(blank=True, default=list, null=True, verbose_name='أكواد البار')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة / Image')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('prix_vente_cache', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('prix_vente_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente_6', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente_8', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente_9', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente_10', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente_12', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente_15', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantite', models.IntegerField(default=0)),
                ('taux_benefice_cache', models.FloatField(blank=True, null=True)),
                ('taux_benefice_3', models.FloatField(blank=True, null=True)),
                ('taux_benefice_5', models.FloatField(blank=True, null=True)),
                ('taux_benefice_6', models.FloatField(blank=True, null=True)),
                ('taux_benefice_8', models.FloatField(blank=True, null=True)),
                ('taux_benefice_9', models.FloatField(blank=True, null=True)),
                ('taux_benefice_10', models.FloatField(blank=True, null=True)),
                ('taux_benefice_12', models.FloatField(blank=True, null=True)),
                ('taux_benefice_15', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True, null=True)),
                ('est_supprime', models.BooleanField(default=False)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.magasin', verbose_name='المحل / Magasin')),
            ],
        ),
    ]
