# Generated by Django 5.2.2 on 2025-06-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='اسم المنتوج')),
                ('famille', models.CharField(max_length=100, verbose_name='العائلة')),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='العلامة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='الصورة')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.magasin', verbose_name='المحل')),
            ],
            options={
                'verbose_name': 'المنتوج',
                'verbose_name_plural': 'المنتوجات',
                'ordering': ['nom'],
            },
        ),
    ]
