# Generated by Django 5.2.2 on 2025-06-10 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['nom'], 'verbose_name': 'المنتوج / Produit', 'verbose_name_plural': 'المنتوجات / Produits'},
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix_vente',
        ),
        migrations.AddField(
            model_name='produit',
            name='codebar',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='كودبار'),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente_1',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='سعر البيع (1 قطعة) / Prix vente (1 pièce)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente_10',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='سعر البيع (10 قطع) / Prix vente (10 pièces)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente_3',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='سعر البيع (3 قطع) / Prix vente (3 pièces)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente_5',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='سعر البيع (5 قطع) / Prix vente (5 pièces)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente_8',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='سعر البيع (8 قطع) / Prix vente (8 pièces)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='famille',
            field=models.CharField(max_length=100, verbose_name='العائلة / Famille'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='صورة / Image'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.magasin', verbose_name='المحل / Magasin'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, max_length=100, verbose_name='العلامة / Marque'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='اسم المنتوج / Nom produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name="سعر الشراء / Prix d'achat"),
        ),
    ]
