# Generated by Django 5.2.2 on 2025-06-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_produit_options_remove_produit_prix_vente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix_vente_1',
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente_cache',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='سعر البيع كاش / Prix vente cash'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_10',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='سعر البيع (10 أشهر) / Prix vente (10 mois)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_3',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='سعر البيع (3 أشهر) / Prix vente (3 mois)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_5',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='سعر البيع (5 أشهر) / Prix vente (5 mois)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_8',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='سعر البيع (8 أشهر) / Prix vente (8 mois)'),
        ),
    ]
