# Generated by Django 5.2.2 on 2025-06-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_remove_produit_prix_vente_1_produit_prix_vente_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(default=0, verbose_name='الكمية / Quantité'),
        ),
    ]
