# Generated by Django 5.2.2 on 2025-06-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_produit_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='codebar',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantite',
        ),
        migrations.AddField(
            model_name='produit',
            name='codes_barres',
            field=models.JSONField(default=list, help_text='Liste des codes-barres sous forme de tableau', verbose_name='أكواد البار'),
        ),
    ]
