# Generated by Django 5.2.2 on 2025-06-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_remove_produit_codebar_remove_produit_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
    ]
