# Generated by Django 5.2.2 on 2025-06-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_produit_est_supprime'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
    ]
