# Generated by Django 5.2.2 on 2025-06-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_produit_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='taux_benefice_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='taux_benefice_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='taux_benefice_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='taux_benefice_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='codes_barres',
            field=models.JSONField(default=list, help_text='Liste des codes-barres', verbose_name='أكواد البار'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
