# Generated by Django 5.2.2 on 2025-06-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_produit_taux_benefice_10_produit_taux_benefice_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='taux_benefice_cache',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
