# Generated by Django 5.0.3 on 2025-07-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_produit_taux_benefice_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
