# Generated by Django 5.0.3 on 2025-07-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0010_produit_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name="سعر الشراء / Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_10',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_5',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_8',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_cache',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='سعر البيع كاش / Prix vente cash'),
        ),
    ]
