# Generated by Django 5.0.3 on 2025-07-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0011_alter_produit_prix_achat_alter_produit_prix_vente_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='codes_barres',
            field=models.JSONField(blank=True, default=list, help_text='Liste des codes-barres', null=True, verbose_name='أكواد البار'),
        ),
    ]
