# Generated by Django 5.0.3 on 2025-08-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0012_alter_produit_codes_barres'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_vente_12',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente_15',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente_6',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente_9',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='taux_benefice_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='taux_benefice_15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='taux_benefice_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='taux_benefice_9',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
