# Generated by Django 5.0.3 on 2025-08-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0013_produit_prix_vente_12_produit_prix_vente_15_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='codes_barres',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='أكواد البار'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_cache',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
