# Generated by Django 5.0.3 on 2025-08-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0014_alter_produit_codes_barres_alter_produit_prix_achat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={},
        ),
    ]
