# Generated by Django 5.2.2 on 2025-08-23 15:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0015_alter_produit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة / Image'),
        ),
    ]
